create table `roles` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `description` varchar(255) null, `level` int not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci;
alter table `roles` add unique `roles_slug_unique`(`slug`);
create table `role_user` (`id` int unsigned not null auto_increment primary key, `role_id` int unsigned not null, `user_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci;
alter table `role_user` add constraint `role_user_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
alter table `role_user` add index `role_user_role_id_index`(`role_id`);
alter table `role_user` add index `role_user_user_id_index`(`user_id`);
create table `permissions` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `description` varchar(255) null, `model` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci;
alter table `permissions` add unique `permissions_slug_unique`(`slug`);
create table `permission_role` (`id` int unsigned not null auto_increment primary key, `permission_id` int unsigned not null, `role_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci;
alter table `permission_role` add constraint `permission_role_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
alter table `permission_role` add constraint `permission_role_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
alter table `permission_role` add index `permission_role_permission_id_index`(`permission_id`);
alter table `permission_role` add index `permission_role_role_id_index`(`role_id`);
create table `permission_user` (`id` int unsigned not null auto_increment primary key, `permission_id` int unsigned not null, `user_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci;
alter table `permission_user` add constraint `permission_user_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
alter table `permission_user` add constraint `permission_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
alter table `permission_user` add index `permission_user_permission_id_index`(`permission_id`);
alter table `permission_user` add index `permission_user_user_id_index`(`user_id`);